name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET environment for building the C# project
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build the Docker image
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 905418195783.dkr.ecr.eu-north-1.amazonaws.com
          ECR_REPOSITORY: csharp-ecr/dataaccess-container
          IMAGE_TAG: latest
        run: |
          # Navigate to the directory containing the Dockerfile
          cd src/DataAccess
          
          # Build the Docker image for the C# application
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
      
          # Push the Docker image to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Optionally, you can add a step to verify the image has been pushed
      - name: Verify Image Pushed
        run: |
          echo "Listing images in ECR repository:"
          aws ecr describe-images --repository-name csharp-ecr/dataaccess-container --region eu-north-1

      # Update the Lambda function to use the new image
      - name: Update Lambda function with new image
        env:
          ECR_REGISTRY: 905418195783.dkr.ecr.eu-north-1.amazonaws.com
          ECR_REPOSITORY: csharp-ecr/dataaccess-container
          IMAGE_TAG: latest
        run: |
          # Update the Lambda function code with the new image URI
          aws lambda update-function-code \
            --function-name DataAccess \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
